[package]
name = "ifs2"
version = "0.0.1"
edition = "2024"

[dependencies]
xxhash-rust = { version = "0.8.15", features = ["xxh32", "xxh3"] }
ctr = "0.9.2"
aes = "0.8.4"
wow-mpq = "0.3.2"
flate2 = "1.1.2"
walkdir = "2.5.0"
bitflags = "2.9.4"